In [ ]:
import numpy as np
import pandas as pd
from osgeo import gdal
import matplotlib.pyplot as plt

In [ ]:
hh_20201209 = gdal.Open('/content/drive/MyDrive/final folder/hh_20201209.tif')
hh_20210112 = gdal.Open('/content/drive/MyDrive/final folder/hh_20210110.tif')
hh_20210211 = gdal.Open('/content/drive/MyDrive/final folder/hh_20210211.tif')
hh_20210227 = gdal.Open('/content/drive/MyDrive/final folder/hh_20210227.tif')

In [ ]:
hh1 = hh_20201209.ReadAsArray().astype(np.float)
hh2 = hh_20210112.ReadAsArray().astype(np.float)
hh3 = hh_20210211.ReadAsArray().astype(np.float)
hh4 = hh_20210227.ReadAsArray().astype(np.float)

In [ ]:
hv_20201209 = gdal.Open('/content/drive/MyDrive/final folder/hv_20201209.tif')
hv_20210112 = gdal.Open('/content/drive/MyDrive/final folder/hv_20210110.tif')
hv_20210211 = gdal.Open('/content/drive/MyDrive/final folder/hv_20210211.tif')
hv_20210227 = gdal.Open('/content/drive/MyDrive/final folder/hv_20210227.tif')



In [ ]:
hv1 = hv_20201209.ReadAsArray().astype(np.float)
hv2 = hv_20210112.ReadAsArray().astype(np.float)
hv3 = hv_20210211.ReadAsArray().astype(np.float)
hv4 = hv_20210227.ReadAsArray().astype(np.float)

In [ ]:
vh_20201209 = gdal.Open('/content/drive/MyDrive/final folder/vh_20201209.tif')
vh_20210112 = gdal.Open('/content/drive/MyDrive/final folder/vh_20210110.tif')
vh_20210211 = gdal.Open('/content/drive/MyDrive/final folder/vh_20200211.tif')
vh_20210227 = gdal.Open('/content/drive/MyDrive/final folder/vh_20210227.tif')

In [ ]:
vh1 = vh_20201209.ReadAsArray().astype(np.float)
vh2 = vh_20210112.ReadAsArray().astype(np.float)
vh3 = vh_20210211.ReadAsArray().astype(np.float)
vh4 = vh_20210227.ReadAsArray().astype(np.float)

In [ ]:
vv_20201209 = gdal.Open('/content/drive/MyDrive/final folder/vv_20201209.tif')
vv_20210112 = gdal.Open('/content/drive/MyDrive/final folder/vv_20210110.tif')
vv_20210211 = gdal.Open('/content/drive/MyDrive/final folder/vv_20210211.tif')
vv_20210227 = gdal.Open('/content/drive/MyDrive/final folder/vv_20210227.tif')

In [ ]:
vv1 = vv_20201209.ReadAsArray().astype(np.float)
vv2 = vv_20210112.ReadAsArray().astype(np.float)
vv3 = vv_20210211.ReadAsArray().astype(np.float)
vv4 = vv_20210227.ReadAsArray().astype(np.float)

In [ ]:
x,y = vv4.shape
print(x)
print(y)

744
1233


In [ ]:
hh2rs = hh2[:742,:1231]
hh2rs.shape
hh3rs = hh3[:742,:1231]
hh3rs.shape
hh4rs = hh4[:742,:1231]
hv2rs = hv2[:742,:1231]
hv3rs = hv3[:742,:1231]
hv4rs = hv4[:742,:1231]
vh2rs = vh2[:742,:1231]
vh3rs = vh3[:742,:1231]
vh4rs = vh4[:742,:1231]
vv2rs = vv2[:742,:1231]
vv3rs = vv3[:742,:1231]
vv4rs = vv4[:742,:1231]

In [ ]:
hh1_reshape = np.reshape(hh1,[742*1231,1],order = 'F')
df = pd.DataFrame(hh1_reshape)
hh2_reshape = np.reshape(hh2rs,[742*1231,1],order = 'F')
df[1] = pd.DataFrame(hh2_reshape)
hh3_reshape = np.reshape(hh3rs,[742*1231,1],order = 'F')
df[2] = pd.DataFrame(hh3_reshape)
hh4_reshape = np.reshape(hh4rs,[742*1231,1],order = 'F')
df[3] = pd.DataFrame(hh4_reshape)
hv1_reshape = np.reshape(hv1,[742*1231,1],order = 'F')
df[4] = pd.DataFrame(hv1_reshape)
hv2_reshape = np.reshape(hv2rs,[742*1231,1],order = 'F')
df[5] = pd.DataFrame(hv2_reshape)
hv3_reshape = np.reshape(hv3rs,[742*1231,1],order = 'F')
df[6] = pd.DataFrame(hv3_reshape)
hv4_reshape = np.reshape(hv4rs,[742*1231,1],order = 'F')
df[7] = pd.DataFrame(hv4_reshape)
vh1_reshape = np.reshape(vh1,[742*1231,1],order = 'F')
df[8] = pd.DataFrame(vh1_reshape)
vh2_reshape = np.reshape(vh2rs,[742*1231,1],order = 'F')
df[9] = pd.DataFrame(vh2_reshape)
vh3_reshape = np.reshape(vh3rs,[742*1231,1],order = 'F')
df[10] = pd.DataFrame(vh3_reshape)
vh4_reshape = np.reshape(vh4rs,[742*1231,1],order = 'F')
df[11] = pd.DataFrame(vh4_reshape)
vv1_reshape = np.reshape(vv1,[742*1231,1],order = 'F')
df[12] = pd.DataFrame(vv1_reshape)
vv2_reshape = np.reshape(vv2rs,[742*1231,1],order = 'F')
df[13] = pd.DataFrame(vv2_reshape)
vv3_reshape = np.reshape(vv3rs,[742*1231,1],order = 'F')
df[14] = pd.DataFrame(vv3_reshape)
vv4_reshape = np.reshape(vv4rs,[742*1231,1],order = 'F')
df[15] = pd.DataFrame(vv4_reshape)


In [ ]:
df

In [ ]:
from PIL import Image
import os

In [ ]:
df1 = (df.loc[df[0]<=0.12])
df1

In [ ]:
df2 = (df.loc[df[0]<=0.2])
df3 = (df2.loc[df2[0]>0.12])
df3



In [ ]:
df4 = (df.loc[df[0]<=0.36])
df5 = (df4.loc[df4[0]>0.2])
df5

In [ ]:
df6 = (df.loc[df[0]<=0.44])
df7 = (df6.loc[df6[0]>0.36])
df7

0         1         2   ...        13        14        15
293     0.360440  0.375320  0.461218  ...  0.277036  0.285397  0.346228
294     0.368764  0.371792  0.429985  ...  0.269087  0.278511  0.345901
407     0.365074  0.444810  0.284430  ...  0.440653  0.211158  0.244981
408     0.383040  0.405028  0.312106  ...  0.400670  0.224882  0.262927
409     0.363274  0.377522  0.328477  ...  0.367435  0.228980  0.276851
...          ...       ...       ...  ...       ...       ...       ...
912804  0.386021  0.386499  0.344183  ...  0.364763  0.327215  0.307383
912805  0.371662  0.394714  0.317997  ...  0.384554  0.320463  0.292348
912845  0.365775  0.445830  0.327080  ...  0.362533  0.281929  0.367556
912846  0.370710  0.454260  0.323791  ...  0.370374  0.274968  0.343228
912847  0.367896  0.435832  0.326562  ...  0.367376  0.264256  0.329923

[33692 rows x 16 columns]

In [ ]:
df8 = (df.loc[df[0]<=0.55])
df9 = (df8.loc[df8[0]>0.44])
df9


In [ ]:
df10 = (df.loc[df[0]<=0.65])
df11 = (df10.loc[df10[0]>0.55])
df11

In [ ]:
df12 = (df.loc[df[0]<=0.75])
df13 = (df12.loc[df12[0]>0.65])    
df13

In [ ]:
df14 = (df.loc[df[0]<=0.85])
df15 = (df14.loc[df14[0]>0.75]) 
df15   

In [ ]:
df16 = (df.loc[df[0]<=0.95])
df17 = (df16.loc[df16[0]>0.85])    
df17

In [ ]:
df18 = (df.loc[df[0]<=1.5])
df19 = (df18.loc[df18[0]>0.95])  
df19  

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
a = np.arange((97327),dtype = np.int)
arrays = df1.values.tolist()
rand = np.random.choice(a,size = 2,replace ='False')
print(arrays[rand[0]])
print(arrays[rand[1]])
print(rand)

[0.11885184794664383, 0.17494447529315948, 0.2592310607433319, 0.5971407294273376, 0.051219046115875244, 0.03572643920779228, 0.06800180673599243, 0.1342071294784546, 0.050045646727085114, 0.03803692013025284, 0.06451113522052765, 0.1380898505449295, 0.11795701831579208, 0.17510128021240234, 0.1976756453514099, 0.33239540457725525]
[0.10061652213335037, 0.17515017092227936, 0.2794349491596222, 0.3966531753540039, 0.02746819518506527, 0.04997771233320236, 0.0895790085196495, 0.10025882720947266, 0.027017133310437202, 0.048811327666044235, 0.08996494859457016, 0.09610733389854431, 0.09676515311002731, 0.11871044337749481, 0.15983140468597412, 0.17374207079410553]
[67530 61346]


In [ ]:
b = arrays[75768]
c = arrays[37961]
carray = np.array(b,dtype = np.float)
barray = np.array(c,dtype = np.float)
carray
barray


In [ ]:
a1 = np.arange((515607),dtype = np.int)
arrays1 = df3.values.tolist()
rand = np.random.choice(a1,size = 2,replace ='False')
print(arrays1[rand[0]])
print(arrays1[rand[1]])
print(rand)

In [ ]:
b1 = arrays1[169536]
c1 = arrays1[342680]
c1array = np.array(b1,dtype = np.float)
b1array = np.array(c1,dtype = np.float)
c1array
b1array


array([0.16242489, 0.2975041 , 0.39006895, 0.49840659, 0.03544148,
       0.05540279, 0.09168975, 0.11959891, 0.03415427, 0.05004091,
       0.08672624, 0.11924151, 0.16345173, 0.21356392, 0.29690823,
       0.32182944])

In [ ]:
a2 = np.arange((251165),dtype = np.int)
arrays2 = df5.values.tolist()
rand = np.random.choice(a2,size = 2,replace ='False')
print(arrays2[rand[0]])
print(arrays2[rand[1]])
print(rand)

[0.3372856080532074, 0.5489248037338257, 0.5100054740905762, 0.5874532461166382, 0.09232266247272491, 0.1413583606481552, 0.08509345352649689, 0.10708776116371155, 0.09992958605289459, 0.14903227984905243, 0.08446285128593445, 0.11488837748765945, 0.3228817582130432, 0.5497128367424011, 0.30193769931793213, 0.3665097653865814]
[0.21188174188137054, 0.2777145206928253, 0.2633502781391144, 0.38859206438064575, 0.08197999000549316, 0.09465191513299942, 0.09080160409212112, 0.14193019270896912, 0.08322098851203918, 0.09968546032905579, 0.08942770212888718, 0.14033114910125732, 0.17674463987350464, 0.25744810700416565, 0.2763311266899109, 0.28581663966178894]
[212503 130063]


In [ ]:
b2 = arrays2[8419]
c2 = arrays2[22711]
c2array = np.array(b2,dtype = np.float)
b2array = np.array(c2,dtype = np.float)
c2array
b2array

In [ ]:
a3 = np.arange((33692),dtype = np.int)
arrays3 = df7.values.tolist()
rand = np.random.choice(a3,size = 2,replace ='False')
print(arrays3[rand[0]])
print(arrays3[rand[1]])
print(rand)

In [ ]:
b3 = arrays3[24114]
c3 = arrays3[25109]
c3array = np.array(b3,dtype = np.float)
b3array = np.array(c3,dtype = np.float)
c3array
b3array

In [ ]:
a4 = np.arange((8844),dtype = np.int)
arrays4 = df9.values.tolist()
rand = np.random.choice(a4,size = 2,replace ='False')
print(arrays4[rand[0]])
print(arrays4[rand[1]])
print(rand)

[0.4449501931667328, 1.005415439605713, 0.5054154992103577, 0.6402284502983093, 0.04079004377126694, 0.08006611466407776, 0.08265065401792526, 0.11478661000728607, 0.03544639050960541, 0.07049726694822311, 0.08291126787662506, 0.11182770133018494, 0.6153373718261719, 1.159905195236206, 0.26952898502349854, 0.34101057052612305]
[0.5073779225349426, 0.6478710174560547, 0.5394091010093689, 0.5366206765174866, 0.08256153017282486, 0.09560365229845047, 0.08931110799312592, 0.09231831878423691, 0.08558063954114914, 0.10432422161102295, 0.08979593217372894, 0.08701828122138977, 0.5103184580802917, 0.6375941634178162, 0.49315348267555237, 0.4702434837818146]
[6320 4638]


In [ ]:
b4 = arrays4[536]
c4 = arrays4[3819]
c4array = np.array(b4,dtype = np.float)
b4array = np.array(c4,dtype = np.float)
c4array
b4array

array([0.48591956, 0.64495552, 0.78496528, 1.15367913, 0.06599028,
       0.04448884, 0.11707361, 0.12194192, 0.06151984, 0.05470994,
       0.11083928, 0.11713503, 0.70093834, 0.78553814, 0.46200311,
       0.39893204])

In [ ]:
a5 = np.arange((2462),dtype = np.int)
arrays5 = df11.values.tolist()
rand = np.random.choice(a5,size = 2,replace ='False')
print(arrays5[rand[0]])
print(arrays5[rand[1]])
print(rand)

[0.5845558047294617, 0.34183090925216675, 0.6962029933929443, 0.9066682457923889, 0.10991641879081726, 0.070929616689682, 0.13163813948631287, 0.14186431467533112, 0.09454016387462616, 0.0745701715350151, 0.12762919068336487, 0.1414511650800705, 0.366271436214447, 0.2783358693122864, 0.4541982412338257, 0.44869664311408997]
[0.6014096140861511, 1.1763819456100464, 0.5489133596420288, 0.7661392688751221, 0.05552138015627861, 0.07357994467020035, 0.08420678228139877, 0.1225471943616867, 0.05700039491057396, 0.06000884249806404, 0.07807408273220062, 0.11541624367237091, 0.6426525712013245, 1.263814926147461, 0.33802530169487, 0.44065606594085693]
[ 163 1793]


In [ ]:
b5 = arrays5[1910]
c5 = arrays5[605]
c5array = np.array(b5,dtype = np.float)
b5array = np.array(c5,dtype = np.float)
c5array
b5array

array([0.55213666, 0.78476167, 0.28823504, 1.61843967, 0.10858058,
       0.07335446, 0.06967835, 0.0918667 , 0.09682995, 0.05962326,
       0.0711979 , 0.08492143, 0.60668874, 0.39211243, 0.28499505,
       1.16952324])

In [ ]:
a6 = np.arange((1450),dtype = np.int)
arrays6 = df13.values.tolist()
rand = np.random.choice(a6,size = 2,replace ='False')
print(arrays6[rand[0]])
print(arrays6[rand[1]])
print(rand)

[0.6851007342338562, 0.7210500836372375, 0.8149034380912781, 0.6918994784355164, 0.10169081389904022, 0.1382981389760971, 0.1459173560142517, 0.13147100806236267, 0.0884290486574173, 0.12877260148525238, 0.14342206716537476, 0.12447667866945267, 0.3835608959197998, 0.34781357645988464, 0.48217636346817017, 0.4186024069786072]
[0.6689965724945068, 0.9275507926940918, 1.3400968313217163, 0.6918380856513977, 0.16142600774765015, 0.17971234023571014, 0.14956389367580414, 0.1518351137638092, 0.1509101688861847, 0.16337063908576965, 0.14792482554912567, 0.14892175793647766, 0.5552554130554199, 0.9269157648086548, 0.5775606036186218, 0.39357897639274597]
[162 831]


In [ ]:
b6 = arrays6[93]
c6 = arrays6[943]
c6array = np.array(b6,dtype = np.float)
b6array = np.array(c6,dtype = np.float)
c6array
b6array

array([0.73974043, 0.71677399, 0.5347625 , 0.55073833, 0.09809441,
       0.0722068 , 0.08281379, 0.0923587 , 0.07227162, 0.06576657,
       0.08023327, 0.08548085, 0.48272198, 0.29113075, 0.42657512,
       0.39375964])

In [ ]:
a7 = np.arange((867),dtype = np.int)
arrays7 = df15.values.tolist()
rand = np.random.choice(a7,size = 2,replace ='False')
print(arrays7[rand[0]])
print(arrays7[rand[1]])
print(rand)

[0.8375716209411621, 0.7233113050460815, 0.4286421537399292, 0.643115758895874, 0.08197192847728729, 0.06804122775793076, 0.06168518587946892, 0.09722112864255905, 0.05236791446805, 0.04929086193442345, 0.055358920246362686, 0.10114092379808426, 0.4284890592098236, 0.5542106628417969, 0.2976568937301636, 0.46393316984176636]
[0.8454606533050537, 1.600297212600708, 0.5971361994743347, 0.7247403264045715, 0.0693231076002121, 0.08203675597906113, 0.07483862340450287, 0.11131899803876877, 0.06354741007089615, 0.08123328536748886, 0.07137704640626907, 0.10655313730239868, 0.6150203347206116, 1.4464560747146606, 0.5495174527168274, 0.5438584089279175]
[717 707]


In [ ]:
b7 = arrays7[417]
c7 = arrays7[359]
c7array = np.array(b7,dtype = np.float)
b7array = np.array(c7,dtype = np.float)
c7array
b7array

array([0.76211625, 0.45864236, 0.62780786, 0.50861537, 0.10747193,
       0.10676809, 0.09411988, 0.09738591, 0.09346981, 0.10162432,
       0.09225821, 0.09605107, 0.79631716, 0.37932307, 0.50980371,
       0.4087323 ])

In [ ]:
a8 = np.arange((615),dtype = np.int)
arrays8 = df17.values.tolist()
rand = np.random.choice(a8,size = 2,replace ='False')
print(arrays8[rand[0]])
print(arrays8[rand[1]])
print(rand)

[0.8522995114326477, 0.6222986578941345, 0.6806915402412415, 0.5178287029266357, 0.10839132964611053, 0.09528792649507523, 0.10889193415641785, 0.10685349255800247, 0.12398870289325714, 0.10487911850214005, 0.10434956103563309, 0.10810008645057678, 0.6610302329063416, 0.5425639748573303, 0.6030646562576294, 0.39465489983558655]
[0.9461134672164917, 1.3113815784454346, 0.876384437084198, 1.0173841714859009, 0.24234747886657715, 0.1688440889120102, 0.13498163223266602, 0.12286095321178436, 0.25902387499809265, 0.1694611757993698, 0.13297346234321594, 0.12663976848125458, 0.787631630897522, 0.6565753817558289, 0.5849010944366455, 0.5994827151298523]
[202 298]


In [ ]:
b8 = arrays8[85]
c8 = arrays8[590]
c8array = np.array(b8,dtype = np.float)
b8array = np.array(c8,dtype = np.float)
c8array
b8array

array([0.93132156, 0.69857073, 0.51835376, 0.44410703, 0.12586723,
       0.12638082, 0.13920332, 0.12978908, 0.13377422, 0.12569521,
       0.1419587 , 0.13157803, 0.94284743, 0.68851209, 0.45321843,
       0.38075766])

In [ ]:
a9 = np.arange((1167),dtype = np.int)
arrays9 = df19.values.tolist()
rand = np.random.choice(a9,size = 2,replace ='False')
print(arrays9[rand[0]])
print(arrays9[rand[1]])
print(rand)

[1.1860311031341553, 1.1541332006454468, 0.6218519806861877, 0.43075716495513916, 0.09778991341590881, 0.08933372050523758, 0.08727920055389404, 0.11399256438016891, 0.12385568767786026, 0.10090683400630951, 0.0893109068274498, 0.10901596397161484, 1.2572429180145264, 1.2751656770706177, 0.5448627471923828, 0.3009984791278839]
[1.4645253419876099, 1.275356650352478, 0.46485766768455505, 0.8209973573684692, 0.0963195413351059, 0.10860627889633179, 0.08350999653339386, 0.0857168436050415, 0.07151283323764801, 0.07948563247919083, 0.079496368765831, 0.07961312681436539, 0.285300612449646, 0.37726742029190063, 0.2451239973306656, 0.3915672302246094]
[ 899 1049]


In [ ]:
b9 = arrays9[85]
c9 = arrays9[590]
c9array = np.array(b9,dtype = np.float)
b9array = np.array(c9,dtype = np.float)
c9array
b9array

array([0.96011525, 1.33338606, 0.94716305, 0.74121559, 0.17274009,
       0.18884465, 0.14973634, 0.14006862, 0.1483268 , 0.15695296,
       0.14434017, 0.12800229, 0.89896971, 0.65174389, 0.61273432,
       0.46326977])

In [ ]:
plt.figure(figsize =(20,10))
plt.plot(carray)
#plt.plot(barray)
plt.plot(c1array)
plt.plot(b1array)
plt.plot(c2array)
plt.plot(b2array)
plt.plot(c4array)
plt.plot(b4array)
plt.plot(c5array)
plt.plot(b5array)
plt.plot(c6array)
#plt.plot(b6array)
plt.plot(c7array)
plt.plot(b7array)
plt.plot(c8array)
plt.plot(b8array)
plt.plot(c9array)
plt.plot(b9array)
plt.ylabel('Back scattering values')
plt.xlabel('time stamp')
plt.legend(['1st reference','2nd reference','3rd reference','4th reference','5th reference','6th rference','7th reference','8th reference','9th reference','10th reference','11th reference','12th reference','13th reference','14th reference','15th reference','16th reference'])
plt.plot([3,3],[0.0,1.8],linestyle = 'dashed')
plt.plot([7,7],[0.0,1.8],linestyle ='dashed')
plt.plot([11,11],[0.0,1.8],linestyle ='dashed')

In [ ]:
def dp(df7,df8,m,n):
    
  
    
    

    #N = df7.shape
    #M = df8.shape
    
    # Initialize the cost matrix
    cost_mat = np.zeros((17, 17))
    for i in range(1, 17):
        cost_mat[i, 0] = np.inf
    for i in range(1, 17):
        cost_mat[0, i] = np.inf

    # Fill the cost matrix while keeping traceback information
    traceback_mat = np.zeros((16, 16))
    for i in range(16):
        for j in range(16):
            penalty = [
                cost_mat[i, j],      # match (0)
                cost_mat[i, j + 1],  # insertion (1)
                cost_mat[i + 1, j]]  # deletion (2)
            i_penalty = np.argmin(penalty)
            cost_mat[i + 1, j + 1] = abs(df7[i]-df8[j]) + penalty[i_penalty]
            traceback_mat[i, j] = i_penalty

    # Traceback from bottom right
    i = 16 - 1
    j = 16 - 1
    path = [(i, j)]
    while i > 0 or j > 0:
        tb_type = traceback_mat[i, j]
        if tb_type == 0:
            # Match
            i = i - 1
            j = j - 1
        elif tb_type == 1:
            # Insertion
            i = i - 1
        elif tb_type == 2:
            # Deletion
            j = j - 1
        path.append((i, j))
        

    # Strip infinity edges from cost_mat before returning
    cost_mat = cost_mat[1:, 1:]
    m.append(cost_mat)
    n.append(path[::-1])
    return m,n

In [ ]:
s =df.values.tolist()

m =[]
n =[]

for k in range(913402):
  list = np.array(s[k],dtype = np.float)
  
  
  dp(carray,list,m,n)
  
  

In [ ]:
h = []
for i in m:
  k =i[-1,-1]
  h.append(k)

In [ ]:
csv = pd.read_csv('/content/drive/MyDrive/output.csv')
data = pd.DataFrame(csv)

# New section

In [ ]:
d = np.reshape(h,[913402,1],order='F')

data[19] = pd.DataFrame(d)
data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/output.csv'

with open(path,'w',encoding = 'utf-8-sig')as f:
  data.to_csv(f)

MessageError: ignored